apiVersion: v1
kind: Service
metadata:
  name: scylla
  labels:
    app.kubernetes.io/name: scylla
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: scylla
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: intra
      port: 7000
      protocol: TCP
    - name: ssl
      port: 7001
      protocol: TCP
    - name: thrift
      port: 9160
      protocol: TCP
    - name: cql
      port: 9042
      protocol: TCP
    - name: jmx
      port: 7199
      protocol: TCP